### ISSUE TITLE
Add a couple questions to our quizzes - HTML, CSS, and JavaScript Quizzes

### ISSUE THREAD

**Issue by terrifricker** [DavidMatthewFraser/easy-to-git#176]
Topic:
easy-to-git is a great repository for making your first contributions.  Add a question or two to one of our quizzes.  There are other ways to contribute as well.

Find more instructions in our [README.md](https://github.com/DavidMatthewFraser/easy-to-git#what-are-starter-projects-that-i-can-work-on)

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by srishtij2000** [comment]
Please assign this to me
