### ISSUE TITLE
Add more challenges

### ISSUE THREAD

**Issue by sauravk7077** [DavidMatthewFraser/easy-to-git#185]
** Challenges **

@DavidMatthewFraser 
Add more challenges or more features in this project.

**Comment by DavidMatthewFraser** [comment]
I would love to, but this is going to have to wait with my busy schedule. 
I apologize for this. 
If you would like to be notified when a new challenge comes out, shoot me an email at davidfraserwebdev@gmail.com.

**Comment by DavidMatthewFraser** [comment]
If you want to add your own challenge, make an issue with your feature request.
