### ISSUE TITLE
Should we allow quality pull requests to this repository to count towards Hacktoberfest 2020?

### ISSUE THREAD

**Issue by terrifricker** [DavidMatthewFraser/easy-to-git#191]
@DavidMatthewFraser 
It might be interesting to let pull requests to this repository count towards [Hacktoberfest 2020](https://hacktoberfest.digitalocean.com/details).  Hacktoberfest participants can receive a free t-shirt by having 4 pull requests accepted to a GitHub repository.  There are quality rules that should be followed, for example just adding a name to the Contributors.md file shouldn't count, but I think the challenges could count.  Here is a summary of the quality rules:

> In line with Hacktoberfest value 2 (Quantity is fun, quality is key), we have provided examples of pull requests that we consider to be low-quality contributions (which we discourage).
> 
> - Pull requests that are automated (e.g. scripted opening pull requests to remove whitespace/fix typos/optimize images).
> - Pull requests that are disruptive (e.g. taking someone else's branch/commits and making a pull request).
> - Pull requests that are regarded by a project maintainer as a hindrance vs. helping.
> - Something that's clearly an attempt to simply +1 your pull request count for October.
> - Last but not least, one pull request to fix a typo is fine, but 5 pull requests to remove a stray whitespace is not.

I think it will be _a lot_ of work, but I have time this month to read, accept or close, and merge all of the pull requests.  I could do all of the 'maintenance'.  I've looked through some of the repositories that are participating, but many still require more than beginning coding.  I think that is why your repository is so great!

I'd like to do it, but I know that you are very busy being back in school.  **If it feels like a weight, let's not do it.**

**Comment by DavidMatthewFraser** [comment]
@terrifricker What a great idea! Would you be willing to talk about this tomorrow over voice chat (I can send a jitzi link). We could talk for like 30 minuets if you would be ok with that.

**Comment by terrifricker** [comment]
Yes. I would love that. You choose time. My day is completely open. You could also choose a time window so you have more flexibility.

**Comment by DavidMatthewFraser** [comment]
I sent a Gitter dm

**Comment by sauravk7077** [comment]
Hey, I would like join as well.
