### ISSUE TITLE
Challenge 1:  Add a cell to our challenge page that includes a quote

### ISSUE THREAD

**Issue by terrifricker** [DavidMatthewFraser/easy-to-git#192]
Create a cell using HTML and CSS that includes your name (or GitHub username), a profile image, and an interesting quote.

Find more instructions in our [README.md](https://github.com/DavidMatthewFraser/easy-to-git#what-are-starter-projects-that-i-can-work-on).  Anyone can work on this issue without being assigned.

**Comment by Alizahh** [comment]
can you please assign me this task?
