### ISSUE TITLE
Add a new Home Page Theme, just change color scheme, or more

### ISSUE THREAD

**Issue by terrifricker** [DavidMatthewFraser/easy-to-git#193]
Decide on your own color scheme, etc. to add to the theme pull down menu.

Find more instructions in our [README.md](https://github.com/DavidMatthewFraser/easy-to-git#what-are-starter-projects-that-i-can-work-on)

**Comment by anushri20** [comment]
Hey, Can I work on this?

**Comment by DavidMatthewFraser** [comment]
@anushri20 Of course! I've added you as an assignee.

**Comment by terrifricker** [comment]
It looks great anushri.  I've requested one small change.

**Comment by sonechca** [comment]
I would like to work on this!! Can I join to work?

**Comment by terrifricker** [comment]
Sure, @sonechca. We'd love to have you join in.

**Comment by srishtij2000** [comment]
Can I work on this issue?
