### ISSUE TITLE
Make a Hacktoberfest Pull Request by doing one of our challenges

### ISSUE THREAD

**Issue by terrifricker** [DavidMatthewFraser/easy-to-git#195]
We have two simple challenges that you can do for making a Hacktoberfest Pull Request.  Find more instructions in our [README.md](https://github.com/DavidMatthewFraser/easy-to-git#what-are-starter-projects-that-i-can-work-on)

Anyone can work on this issue without being assigned.

**Comment by PravunathSingh** [comment]
Hey, @terrifricker I would like to work on this issue, would you please assign it to me?

**Comment by terrifricker** [comment]
Yes, of course.  Go right ahead. I'm not at my computer to be able to assign you.

**Comment by PravunathSingh** [comment]
Alright!!

**Comment by DavidMatthewFraser** [comment]
I've assigned you @PravunathSingh

**Comment by PravunathSingh** [comment]
Alright @DavidMatthewFraser thanks for assigning me, currently I'm caught up in some work, as soon as I finish that I'll start working on it ASAP

**Comment by DavidMatthewFraser** [comment]
@PravunathSingh you have until Oct 31 😋

**Comment by terrifricker** [comment]
@PravunathSingh 
You are still welcome to work on this issue, but I am going to remove you from the Assigned list, so it is clear that other workers can work on it as well.

**Comment by sauravk7077** [comment]
Hey, assign me to the water tracker project (if that's possible).

**Comment by DavidMatthewFraser** [comment]
@sauravk7077 Sure, just make an Issue for some things that need to be added/improved/fixed with the water tracker.
