### ISSUE TITLE
Once you have made a successful pull request, add yourself to the Contributors Panel

### ISSUE THREAD

**Issue by terrifricker** [DavidMatthewFraser/easy-to-git#196]
Find more instructions in our [README.md](https://github.com/DavidMatthewFraser/easy-to-git#what-are-starter-projects-that-i-can-work-on)

**Comment by PravunathSingh** [comment]
Hey, @terrifricker I would like to work on this issue, would you please assign it to me?

**Comment by terrifricker** [comment]
You can do this one as soon as I have accepted your first pull request.

**Comment by sonechca** [comment]
Hi, I wanna work on this issue. Can I join to do it? I wanna be a contributor :)

**Comment by terrifricker** [comment]
@sonechca Welcome!  You can do this as well as one of the other issues so you will be contributing more than adding yourself to the list. That way you can do two pull requests.

**Comment by terrifricker** [comment]
@sonechca Challenge One uses html and css. Adding a couple questions to our quiz by adding the to quizQuestions.js. You just need to follow the JavaScript syntax that is already there and type in your new questions, possible answers (multiple choice), and correct answer. 

Please don't hesitate to ask questions here.

**Comment by Adityachaturvedi2906** [comment]
hey! can you please assign me?

**Comment by terrifricker** [comment]
@Adityachaturvedi2906 Yes!  Thanks for joining in.

**Comment by Adityachaturvedi2906** [comment]
Hey, @terrifricker I just submitted my PR kindly review it.
