### ISSUE TITLE
Fade out two images on the Solar System page to make room for others

### ISSUE THREAD

**Issue by terrifricker** [DavidMatthewFraser/easy-to-git#200]
Challenge 2 entails putting an animated image on the page.  It is now very full.  Make an image or two fade from the page, so that others can fade in a new object.  Anyone can work on this issue without being assigned, but please comment below with the id(s) of the images you are working on so there is no duplication.

**Comment by sauravk7077** [comment]
Why don't you increase the height of the page instead of fading it.
