### ISSUE TITLE
Quiz App Bug

### ISSUE THREAD

**Issue by sauravk7077** [DavidMatthewFraser/easy-to-git#203]
On having a long question, the quiz app breaks into two.

**To Reproduce**
1. Go to the Quiz app
2. Click on HTML questions
3. Answer until you reach question number 17.

**Screenshots**
![image](https://user-images.githubusercontent.com/17443674/95531073-4392c480-09fd-11eb-8fc5-7b6654598120.png)

**Desktop:**
 - OS: Windows
 - Browser : Mozilla
 - Version: 82.02b

**Comment by terrifricker** [comment]
@sauravk7077 , do you want to fix it?

**Comment by sauravk7077** [comment]
Yep
