### ISSUE TITLE
Make the themes that change the home page, change the Widgets page, too.

### ISSUE THREAD

**Issue by terrifricker** [DavidMatthewFraser/easy-to-git#223]
There is a pull down menu "Choose Theme" on the easytogit.com home page that makes changes to the home page.  Change the Widgets page so that it changes themes, too.

**Comment by sauravk7077** [comment]
I want to help. To do this we must have a common structure and class names.

**Comment by terrifricker** [comment]
@sauravk, you are being so helpful, but I'd like to leave this open for anyone else to work on at this point.  Please, keep working on your Water Tracker instead.
Thank you

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by DavidMatthewFraser** [comment]
At this point what needs to be done is some fine tuning to the changes I've made & updated instructions on how to add a theme. Now to add a theme, you must modify index.html, global/js/themes.js, and home-page/themePicker.js. Updated instructions would be very appreciated :)
