### ISSUE TITLE
Bug introduced into useful-links

### ISSUE THREAD

**Issue by terrifricker** [DavidMatthewFraser/easy-to-git#245]
**Describe the bug**
When hovering over a book, the animation works, but the backside disappears after just a second or so.  They behave properly in Firefox, but not Safari or Chrome.

**To Reproduce**
1. Starting at home page
2. Click Useful Links
3. Scroll down to the Books images
4. Hover

**Expected behavior**
When hovering over a book cover image, the book should flip to show the description of the book until you are no longer hovering.

**Desktop (please complete the following information):**
 - OS: Mojave 10.14.6
 - Browser: Safari 14.0, Chrome 86.0.4240.80 , FireFox 81.0.2 

**Additional context**
I think I made this happen.  I think that I ended up merging a pull request that anuran-ux had closed. Sorry.  I cannot find the bug.

**Comment by sauravk7077** [comment]
It works fine in Firefox 82.0b9, Chrome 86.0.4240.75 and Edge 86.0.622.43.

**Comment by DavidMatthewFraser** [comment]
If you hover over the  books : Javascript for Kids, Javascript & JQuery, Cracking the Coding Interview, the text will disappear after a split secon in Chrome 85.0.4183.121

**Comment by DavidMatthewFraser** [comment]
@sauravk7077 yes it works in firefox, but chrome...
