### ISSUE TITLE
Extra Blank List under Youtube channels in Useful links

### ISSUE THREAD

**Issue by kmlhsn** [DavidMatthewFraser/easy-to-git#270]
**Describe the bug**
There are Extra Blank HTML list under "YouTube Channel", "Podcasts", "Platforms for code challenges", "Mobile apps", "Games" in "Useful Links" page
**To Reproduce**
1. Go to http://easytogit.com/
2. Scroll down to bottom
3. Click on "Useful Links"
4. Scroll Down to "YouTube channels"

**Expected behavior**
There Should not have any Extra Blank HTML List

**Screenshots**
![image](https://user-images.githubusercontent.com/32615215/97435791-22156080-194b-11eb-9e90-37d16171599c.png)

**Desktop (please complete the following information):**
Windows 10
Mozilla FireFox
82
**Smartphone (please complete the following information):**

**Additional context**

**Comment by terrifricker** [comment]
kmlhsn, thank you for the very clear issue report.  Would you like to work on this yourself?
