### ISSUE TITLE
New Project - Platform Game

### ISSUE THREAD

**Issue by sauravk7077** [DavidMatthewFraser/easy-to-git#280]
**Platform Game**
I want to ask for a new challenge in which we make a platform game like [Dark Blue](http://www.lessmilk.com/game/dark-blue/)

**Libraries**
HTML Canvas, HTML, CSS, JS

@DavidMatthewFraser @terrifricker

**Comment by DavidMatthewFraser** [comment]
Sounds like a fun project, but it is not inline with the basic goal of of this repo (teaching git basics)
