### ISSUE TITLE
Biscuit Clicker

### ISSUE THREAD

**Issue by sauravk7077** [DavidMatthewFraser/easy-to-git#281]
Biscuit clicker.
I want to ask for a new challenge in which we make a simple game using basic like [Cookie clicker](https://orteil.dashnet.org/experiments/cookie/).

Libraries
HTML, CSS, JS

@DavidMatthewFraser @terrifricker

**Comment by DavidMatthewFraser** [comment]
That sounds like a really fun project!
Again, it is not really related to teaching beginners Git/Github. 
We are also not really looking for more projects right now given Terri and I's busy personal schedules. Thanks!

**Comment by sauravk7077** [comment]
Why don't you give the responsibility to someone?
