### ISSUE TITLE
'Comment Carousel' is warped on mobile

### ISSUE THREAD

**Issue by DavidMatthewFraser** [DavidMatthewFraser/easy-to-git#49]
<img width="376" alt="Screen Shot 2020-08-10 at 5 51 34 PM" src="https://user-images.githubusercontent.com/47202564/89842230-47f04d80-db32-11ea-8ad2-57951985df69.png">

**Comment by benjithorpe** [comment]
fixed it

![Annotation 2020-08-13 035313](https://user-images.githubusercontent.com/61359802/90092472-8fd0c980-dd18-11ea-8542-85417b9dd6ed.png)

**Comment by DavidMatthewFraser** [comment]
Cheers! Targeting the font size with a media query does make it fit better on mobile!
