### ISSUE TITLE
After Changing the text of Instructions-2.txt, a 404 error is thrown when trying to access the instructions

### ISSUE THREAD

**Issue by DavidMatthewFraser** [DavidMatthewFraser/easy-to-git#64]
The popup **was functional** after I originally merged it.

After changing some text in the Instructions-2.txt (**committing directly to master** so there is not a PR) a 404 error is thrown when trying to access the instructions:

It also **works on vs code live** server so I'm not sure what it could be.

<img width="982" alt="Screen Shot 2020-08-12 at 9 34 02 PM" src="https://user-images.githubusercontent.com/47202564/90091426-9264fc00-dce3-11ea-983c-031264e9bb01.png">

I hate to leave code broken, but I gotta sleep 😴

**Comment by SyntappZ** [comment]
fixed! the txt file had an uppercase I on Instructions but the fetch was lowercase

**Comment by DavidMatthewFraser** [comment]
Cheers!
