### ISSUE TITLE
Should we add a Contributing.md?

### ISSUE THREAD

**Issue by misterybodon** [DavidMatthewFraser/easy-to-git#71]
If we move to insights -> community ([press here for short](https://github.com/DavidMatthewFraser/easy-to-git/community)) We'll find one of the best practices is to create a **contributing.md** file. There are some other best practices we could look into.

Yet this project's main topic is to contribute, so it'd be reasonable to keep the README.md file like that. 

I'm just raising this issue so it can be discussed, and also just to raise an issue.

- [x] create a **contributing.md** file ?

**Comment by DavidMatthewFraser** [comment]
Is this a matter of changing contributors.md to contrubting.md or is this somethiing else entirely?

**Comment by misterybodon** [comment]
Yep, so keep this one open for a while? As for one first step we could split the readme, move some contrib stuff to contribution.md, if you like. I've seen you created the files already :-)

**Comment by misterybodon** [comment]
Here is a random example of how a contributing file looks like, from [simpleicons,]([url](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)) a library of svg icons you can take for free :-)

**Comment by DavidMatthewFraser** [comment]
Do you think we should replace all instances of fontaweesome w/ simpleicons??

Their contribution file looks slick ... and helpful. I think something like that is a good thing to strive for. 
Again thanks for raising the issue! I'll leave it open for now while we figure some of this stuff out. 

I'll merge the contributing.md file rn
